### ISSUE TITLE
Dump system

### ISSUE THREAD

**Issue by fjtrujy** [EliasKotlyar/Monsieur-Cuisine-Connect-Hack#4]
Hello,
Looks like when I was doing the backup of the system partition something was wrong and I didn´t notice it.

Now I have the Monsieur Cuisine in a loop it doesn´t start, Im trying to recover it with the backup that I did but is still now working.

could send to my the dump of the system partition?

Thanks

**Comment by EliasKotlyar** [comment]
Hello Fjtrujy,

I am not sure if i am allowed to dump the whole system partition here, however you can message me privatly, and i can share mines for you personally. 

Greatings
Elias

**Comment by fjtrujy** [comment]
Hello @EliasKotlyar,
In the end, I had a friend that bought the Monsieur Cuisine and I grab the system partition from there.
Thank you very much anyway.
I have completed the hack!

**Comment by EmilEmilchen** [comment]
I ran in the exact same problem, somehow my backup of the boot partition seems to have gotten corrupted in some way and now I cant boot anymore. I would love if anyone could provide me with the whole system dump or at least the boot partition.
