### ISSUE TITLE
Protection against loss of warranty 

### ISSUE THREAD

**Issue by maciey** [EliasKotlyar/Monsieur-Cuisine-Connect-Hack#40]
Hi - I would like to be able to add my own recipes to the device. I am going to upload a new soft. But I have a dilemma - my device is still 2.5 years out of warranty. If it breaks down, can I still restore the old software version?

Except of course if the device is not working at all, then it is probably impossible :(

Is there any risk here that the device could be completely spoilt by the new software?

**Comment by bobstar-fr** [comment]
Hello 
what software is this?
Is this a Monsieur Cuisine Connect or a Monsieur Cuisine Smart
If you master programming, there is always a solution...

**Comment by maciey** [comment]
Im am programmer and could write own app / easy receipts uploader 
But my question was more about flashing - how safe is that and how easy I can revert it in case I need use warranty?

**Comment by bobstar-fr** [comment]
in computer science, zero risk does not exist even if you are a professional.
take your responsibilities if you are able, otherwise refrain.

**Comment by maciey** [comment]
As a scientific mind, I expected a more precise and not philosophical answer.... :)

I only asked if it is possible to reverse the flashing process so that the device meets the warranty ...

Is anyone able to give a zero-one answer to this ?

**Comment by bobstar-fr** [comment]
if you are a scientist you must know how to do it and know that zero risk does not exist.... take your responsibilities.... no one will tell you that it is 100% possible that a bricked device can be recovered.
in addition the device is under warranty... wait until the end of the warranty before tinkering.

**Comment by maciey** [comment]
My English must be worse than I thought.... 
My intention was to find out if it was possible to reverse the flashing process and not to assess the possible risk(s) involved. 

I'm not shaking my head before a possible change / risk - I'm just checking the possibility of reducing the risk / reversing the changes.

**Comment by bobstar-fr** [comment]
No one will confirm that a rollback is possible on a bricked device... the answer is clearly no!...

**Comment by maciey** [comment]
I didnt ask about bricked device. I was looking way to restore firmware if engine fails so I can return device do seller without any software modification. But never mind... Im tired this discussion - so closing it

**Comment by bobstar-fr** [comment]
You are right, close the discussion since you don't want to understand anything I'm telling you...
Engine fail = bricked engine.... 
If for you an MCC whith engine fail is not a bricked device in programming sense of the term, you will have to review your basics... 
Personally I will no longer respond on this subject.
