### ISSUE TITLE
Login blocked - asking wifi (despite connected)

### ISSUE THREAD

**Issue by mickkael** [EliasKotlyar/Monsieur-Cuisine-Connect-Hack#44]
![PXL_20240827_121511768.jpg](https://github.com/user-attachments/assets/18bfab67-f0d7-4eb2-b4ed-4bdf18ff7db8)

The wifi is connected successfully, but I can't connect my account, it is asking for wifi. Anyone has manage to clear this issue ?

I have entered the factory mode, the wifi is ok, connected, but the download and upload test are failing.

I have tried the phone tethering as wifi as well, same issue.

I'm living overseas, not in any of the listed countries, could it be the issue ?

**Comment by mickkael** [comment]
I have resolved the issue if anyone is having the same:
There is an IP restriction for the monsieur cuisine services. Only IPs within Europe are allowed.
I've setup a vpn on my router and connected the monsieur cuisine to this router, and the problem disappear

**Comment by Nala882** [comment]
Hello,
I have the same problem, im unable to connect to wifi, i have tried Vpn which is on my phone, giving connection to the machine, but always unable to connect to wifi. Although i have managed to update it twice recently, and from time to time i give new recepies.....
Anyyy advise? Its very frustrating
