### ISSUE TITLE
Exit the MC App without reboot?

### ISSUE THREAD

**Issue by makefu** [EliasKotlyar/Monsieur-Cuisine-Connect-Hack#7]
Hey, at first thanks so much for your writeup.
I am curious if there is a way to exit the MC app without a hard reset or adb. For some reason the Android Icons are not visible when the app is started

**Comment by EliasKotlyar** [comment]
just go to "recipes" search. As soon as the keyboard pops up, you will be able to see the buttons

**Comment by makefu** [comment]
@EliasKotlyar awesome, thanks! I will prepare a PR for the documentation.

**Comment by ximocat** [comment]
@EliasKotlyar Is it possible to exit the application without flashing the device?

**Comment by makefu** [comment]
@ximocat MC App the only application (and therefore launcher) installed on the device. After an exit the app would simply start anew
